/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LinksRouteImport } from './routes/links'
import { Route as IndexRouteImport } from './routes/index'

const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/privacidade': typeof PrivacidadeRoute
  '/showroom': typeof ShowroomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/privacidade': typeof PrivacidadeRoute
  '/showroom': typeof ShowroomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/privacidade': typeof PrivacidadeRoute
  '/showroom': typeof ShowroomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/links' | '/privacidade' | '/showroom'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/links' | '/privacidade' | '/showroom'
  id: '__root__' | '/' | '/links' | '/privacidade' | '/showroom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinksRoute: typeof LinksRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ShowroomRoute: typeof ShowroomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinksRoute: LinksRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ShowroomRoute: ShowroomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
