/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LinksRouteImport } from './routes/links'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBootstrapAdminsRouteImport } from './routes/api/public/bootstrap-admins'

const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminsRoute =
  ApiPublicBootstrapAdminsRouteImport.update({
    id: '/api/public/bootstrap-admins',
    path: '/api/public/bootstrap-admins',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/privacidade': typeof PrivacidadeRoute
  '/showroom': typeof ShowroomRoute
  '/api/public/bootstrap-admins': typeof ApiPublicBootstrapAdminsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/privacidade': typeof PrivacidadeRoute
  '/showroom': typeof ShowroomRoute
  '/api/public/bootstrap-admins': typeof ApiPublicBootstrapAdminsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/privacidade': typeof PrivacidadeRoute
  '/showroom': typeof ShowroomRoute
  '/api/public/bootstrap-admins': typeof ApiPublicBootstrapAdminsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/links'
    | '/privacidade'
    | '/showroom'
    | '/api/public/bootstrap-admins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/links'
    | '/privacidade'
    | '/showroom'
    | '/api/public/bootstrap-admins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/links'
    | '/privacidade'
    | '/showroom'
    | '/api/public/bootstrap-admins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LinksRoute: typeof LinksRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ShowroomRoute: typeof ShowroomRoute
  ApiPublicBootstrapAdminsRoute: typeof ApiPublicBootstrapAdminsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admins': {
      id: '/api/public/bootstrap-admins'
      path: '/api/public/bootstrap-admins'
      fullPath: '/api/public/bootstrap-admins'
      preLoaderRoute: typeof ApiPublicBootstrapAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LinksRoute: LinksRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ShowroomRoute: ShowroomRoute,
  ApiPublicBootstrapAdminsRoute: ApiPublicBootstrapAdminsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
